/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param height The height of the attached trolley
 * @param id The id of the attached trolley
 * @param length The length of the attached trolley
 * @param offsetLockedWheels The distance from front of the attached trolley to the locked wheels
 * @param width The width of the attached trolley
 */
@Serializable@Serializable

data class Cart (

    /* The height of the attached trolley */
    @SerialName(value = "height") val height: kotlin.Float? = null,

    /* The id of the attached trolley */
    @SerialName(value = "id") val id: kotlin.Float? = null,

    /* The length of the attached trolley */
    @SerialName(value = "length") val length: kotlin.Float? = null,

    /* The distance from front of the attached trolley to the locked wheels */
    @SerialName(value = "offset_locked_wheels") val offsetLockedWheels: kotlin.Float? = null,

    /* The width of the attached trolley */
    @SerialName(value = "width") val width: kotlin.Float? = null

)

