/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param errorCode The error in machine format
 * @param errorHuman The error in human friendly format
 */
@Serializable@Serializable

data class Error (

    /* The error in machine format */
    @SerialName(value = "error_code") val errorCode: kotlin.String? = null,

    /* The error in human friendly format */
    @SerialName(value = "error_human") val errorHuman: kotlin.String? = null

)

