/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param code The error code
 * @param description Description of the error
 * @param module The module reporting the error
 */
@Serializable@Serializable

data class Errors (

    /* The error code */
    @SerialName(value = "code") val code: kotlin.Long? = null,

    /* Description of the error */
    @SerialName(value = "description") val description: kotlin.String? = null,

    /* The module reporting the error */
    @SerialName(value = "module") val module: kotlin.String? = null

)

