/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param actions 
 * @param color The color associated with this area
 * @param id The type of area
 * @param image 
 * @param legacyName 
 * @param name A nice name associated with this area action
 */
@Serializable@Serializable

data class GetAreaEventsDefinitions (

    @SerialName(value = "actions") val actions: kotlin.String? = null,

    /* The color associated with this area */
    @SerialName(value = "color") val color: kotlin.String? = null,

    /* The type of area */
    @SerialName(value = "id") val id: kotlin.Long? = null,

    @SerialName(value = "image") val image: kotlin.String? = null,

    @SerialName(value = "legacyName") val legacyName: kotlin.String? = null,

    /* A nice name associated with this area action */
    @SerialName(value = "name") val name: kotlin.String? = null

)

