/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param guid The global id unique across robots that identifies this area
 * @param map The url to the map this area belongs to
 * @param name A name associated with this area
 * @param typeId The type of area
 * @param url The URL of the resource
 */
@Serializable@Serializable

data class GetAreaEvents (

    /* The global id unique across robots that identifies this area */
    @SerialName(value = "guid") val guid: kotlin.String? = null,

    /* The url to the map this area belongs to */
    @SerialName(value = "map") val map: kotlin.String? = null,

    /* A name associated with this area */
    @SerialName(value = "name") val name: kotlin.String? = null,

    /* The type of area */
    @SerialName(value = "type_id") val typeId: kotlin.Long? = null,

    /* The URL of the resource */
    @SerialName(value = "url") val url: kotlin.String? = null

)

