/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param actionType 
 * @param description 
 * @param descriptions 
 * @param help 
 * @param missionGroupId 
 * @param name 
 * @param parameters 
 */
@Serializable@Serializable

data class GetActionDefinitions (

    @SerialName(value = "action_type") val actionType: kotlin.String? = null,

    @SerialName(value = "description") val description: kotlin.String? = null,

    @SerialName(value = "descriptions") val descriptions: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "help") val help: kotlin.String? = null,

    @SerialName(value = "mission_group_id") val missionGroupId: kotlin.String? = null,

    @SerialName(value = "name") val name: kotlin.String? = null,

    @SerialName(value = "parameters") val parameters: kotlin.collections.List<kotlin.String>? = null

)

