/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param actions 
 * @param createdBy The url to the description of the type of this position
 * @param createdById The global id of the user who created this entry
 * @param guid The global id unique across robots that identifies this area
 * @param map The url to the map this area belongs to
 * @param mapId The id of the map this area belongs to
 * @param name A name associated with this area
 * @param polygon The list of coordinates in the area polygon
 * @param typeId The type of area
 */
@Serializable@Serializable

data class GetAreaEvent (

    @SerialName(value = "actions") val actions: kotlin.String? = null,

    /* The url to the description of the type of this position */
    @SerialName(value = "created_by") val createdBy: kotlin.String? = null,

    /* The global id of the user who created this entry */
    @SerialName(value = "created_by_id") val createdById: kotlin.String? = null,

    /* The global id unique across robots that identifies this area */
    @SerialName(value = "guid") val guid: kotlin.String? = null,

    /* The url to the map this area belongs to */
    @SerialName(value = "map") val map: kotlin.String? = null,

    /* The id of the map this area belongs to */
    @SerialName(value = "map_id") val mapId: kotlin.String? = null,

    /* A name associated with this area */
    @SerialName(value = "name") val name: kotlin.String? = null,

    /* The list of coordinates in the area polygon */
    @SerialName(value = "polygon") val polygon: kotlin.collections.List<kotlin.String>? = null,

    /* The type of area */
    @SerialName(value = "type_id") val typeId: kotlin.Long? = null

)

