/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param actionType A name associated with this area action
 * @param actionTypeId The type of area action
 * @param help A description of this action
 * @param limit The amount of actions of this type we can add.
 * @param name A nice name associated with this area action
 * @param parameters 
 */
@Serializable@Serializable

data class GetAreaActionDefinitions (

    /* A name associated with this area action */
    @SerialName(value = "action_type") val actionType: kotlin.String? = null,

    /* The type of area action */
    @SerialName(value = "action_type_id") val actionTypeId: kotlin.Long? = null,

    /* A description of this action */
    @SerialName(value = "help") val help: kotlin.String? = null,

    /* The amount of actions of this type we can add. */
    @SerialName(value = "limit") val limit: kotlin.Long? = null,

    /* A nice name associated with this area action */
    @SerialName(value = "name") val name: kotlin.String? = null,

    @SerialName(value = "parameters") val parameters: kotlin.collections.List<kotlin.String>? = null

)

