/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param createdBy The url to the description of the type of this position
 * @param createdById The global id of the user who created this entry
 * @param guid The global unique id across robots that identifies this bluetooth device
 * @param hardwareId The hardware id string for this bluetooth device
 * @param name The name of the bluetooth device
 * @param type Parameter to filter bluetooth devices
 */
@Serializable@Serializable

data class GetBluetoothRelay (

    /* The url to the description of the type of this position */
    @SerialName(value = "created_by") val createdBy: kotlin.String? = null,

    /* The global id of the user who created this entry */
    @SerialName(value = "created_by_id") val createdById: kotlin.String? = null,

    /* The global unique id across robots that identifies this bluetooth device */
    @SerialName(value = "guid") val guid: kotlin.String? = null,

    /* The hardware id string for this bluetooth device */
    @SerialName(value = "hardware_id") val hardwareId: kotlin.String? = null,

    /* The name of the bluetooth device */
    @SerialName(value = "name") val name: kotlin.String? = null,

    /* Parameter to filter bluetooth devices */
    @SerialName(value = "type") val type: kotlin.String? = null

)

