/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param cartCalibration The url to the calibration of this cart
 * @param cartCalibrationId The id of the calibration for this cart has
 * @param cartType The url to the type of this cart
 * @param cartTypeId The id of the type of this cart
 * @param createdBy The url to the description of the type of this position
 * @param createdById The global id of the user who created this entry
 * @param guid The global id unique across robots that identifies this cart
 * @param name The name of the cart
 */
@Serializable@Serializable

data class GetCart (

    /* The url to the calibration of this cart */
    @SerialName(value = "cart_calibration") val cartCalibration: kotlin.String? = null,

    /* The id of the calibration for this cart has */
    @SerialName(value = "cart_calibration_id") val cartCalibrationId: kotlin.String? = null,

    /* The url to the type of this cart */
    @SerialName(value = "cart_type") val cartType: kotlin.String? = null,

    /* The id of the type of this cart */
    @SerialName(value = "cart_type_id") val cartTypeId: kotlin.String? = null,

    /* The url to the description of the type of this position */
    @SerialName(value = "created_by") val createdBy: kotlin.String? = null,

    /* The global id of the user who created this entry */
    @SerialName(value = "created_by_id") val createdById: kotlin.String? = null,

    /* The global id unique across robots that identifies this cart */
    @SerialName(value = "guid") val guid: kotlin.String? = null,

    /* The name of the cart */
    @SerialName(value = "name") val name: kotlin.String? = null

)

