/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param cartCalibration The url to the calibration of this cart
 * @param cartType The url to the type of this cart
 * @param guid The global id unique across robots that identifies this cart
 * @param name The name of the cart
 * @param url The URL of the resource
 */
@Serializable@Serializable

data class GetCarts (

    /* The url to the calibration of this cart */
    @SerialName(value = "cart_calibration") val cartCalibration: kotlin.String? = null,

    /* The url to the type of this cart */
    @SerialName(value = "cart_type") val cartType: kotlin.String? = null,

    /* The global id unique across robots that identifies this cart */
    @SerialName(value = "guid") val guid: kotlin.String? = null,

    /* The name of the cart */
    @SerialName(value = "name") val name: kotlin.String? = null,

    /* The URL of the resource */
    @SerialName(value = "url") val url: kotlin.String? = null

)

