/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param createdBy The url to the description of the type of this position
 * @param createdById The global id of the user who created this entry
 * @param guid The global id unique across robots that identifies this cart type
 * @param height The height of carts of this type
 * @param length The length of carts of this type
 * @param name The name of the cart type
 * @param offsetLockedWheels The offset from the center of the robot to the locked wheels of carts of this type
 * @param width The width of carts of this type
 */
@Serializable@Serializable

data class GetCartType (

    /* The url to the description of the type of this position */
    @SerialName(value = "created_by") val createdBy: kotlin.String? = null,

    /* The global id of the user who created this entry */
    @SerialName(value = "created_by_id") val createdById: kotlin.String? = null,

    /* The global id unique across robots that identifies this cart type */
    @SerialName(value = "guid") val guid: kotlin.String? = null,

    /* The height of carts of this type */
    @SerialName(value = "height") val height: kotlin.Float? = null,

    /* The length of carts of this type */
    @SerialName(value = "length") val length: kotlin.Float? = null,

    /* The name of the cart type */
    @SerialName(value = "name") val name: kotlin.String? = null,

    /* The offset from the center of the robot to the locked wheels of carts of this type */
    @SerialName(value = "offset_locked_wheels") val offsetLockedWheels: kotlin.Float? = null,

    /* The width of carts of this type */
    @SerialName(value = "width") val width: kotlin.Float? = null

)

