/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param date 
 * @param distance 
 */
@Serializable@Serializable

data class GetDistanceStatistics (

    @SerialName(value = "date") val date: kotlin.String? = null,

    @SerialName(value = "distance") val distance: kotlin.Float? = null

)

