/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param createdBy The url to the user that created the dashboard
 * @param createdById The global id of the user who created this entry
 * @param fleetDashboard 
 * @param guid The global id unique across robots that identifies this dashboard
 * @param name The name of this dashboard
 * @param widgets The url to the possible widgets. if the dashboard does not have any widgets then this field is empty
 */
@Serializable@Serializable

data class GetDashboard (

    /* The url to the user that created the dashboard */
    @SerialName(value = "created_by") val createdBy: kotlin.String? = null,

    /* The global id of the user who created this entry */
    @SerialName(value = "created_by_id") val createdById: kotlin.String? = null,

    @SerialName(value = "fleet_dashboard") val fleetDashboard: kotlin.Boolean? = null,

    /* The global id unique across robots that identifies this dashboard */
    @SerialName(value = "guid") val guid: kotlin.String? = null,

    /* The name of this dashboard */
    @SerialName(value = "name") val name: kotlin.String? = null,

    /* The url to the possible widgets. if the dashboard does not have any widgets then this field is empty */
    @SerialName(value = "widgets") val widgets: kotlin.String? = null

)

