/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param dashboardId The guid of the dashboard this widget belongs to
 * @param guid The global id unique across robots that identifies this widget
 * @param url The URL of the resource
 */
@Serializable@Serializable

data class GetDashboardWidgets (

    /* The guid of the dashboard this widget belongs to */
    @SerialName(value = "dashboard_id") val dashboardId: kotlin.String? = null,

    /* The global id unique across robots that identifies this widget */
    @SerialName(value = "guid") val guid: kotlin.String? = null,

    /* The URL of the resource */
    @SerialName(value = "url") val url: kotlin.String? = null

)

