/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param guid The global id unique across robots that identifies this dashboard
 * @param name The name of this dashboard
 * @param url The URL of the resource
 * @param widgets The url to the possible widgets. if the dashboard does not have any widgets then this field is empty
 */
@Serializable@Serializable

data class GetDashboards (

    /* The global id unique across robots that identifies this dashboard */
    @SerialName(value = "guid") val guid: kotlin.String? = null,

    /* The name of this dashboard */
    @SerialName(value = "name") val name: kotlin.String? = null,

    /* The URL of the resource */
    @SerialName(value = "url") val url: kotlin.String? = null,

    /* The url to the possible widgets. if the dashboard does not have any widgets then this field is empty */
    @SerialName(value = "widgets") val widgets: kotlin.String? = null

)

