/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param dashboard The url to the dashboard where this widget belongs.
 * @param dashboardId The guid of the dashboard this widget belongs to
 * @param guid The global id unique across robots that identifies this widget
 * @param settings Widgets configuration encoded base 64 in json
 */
@Serializable@Serializable

data class GetDashboardWidget (

    /* The url to the dashboard where this widget belongs. */
    @SerialName(value = "dashboard") val dashboard: kotlin.String? = null,

    /* The guid of the dashboard this widget belongs to */
    @SerialName(value = "dashboard_id") val dashboardId: kotlin.String? = null,

    /* The global id unique across robots that identifies this widget */
    @SerialName(value = "guid") val guid: kotlin.String? = null,

    /* Widgets configuration encoded base 64 in json */
    @SerialName(value = "settings") val settings: kotlin.String? = null

)

