/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param guid The global id unique across robots that identifies this docking offset
 * @param orientationOffset The orientation offset with respect to the docking marker
 * @param posId The global id refering to the position that this offset belongs to
 * @param position The url to the position
 * @param xOffset The x-offset with respect to the docking marker
 * @param yOffset The y-offset with respect to the docking marker
 */
@Serializable@Serializable

data class GetDockingOffset (

    /* The global id unique across robots that identifies this docking offset */
    @SerialName(value = "guid") val guid: kotlin.String? = null,

    /* The orientation offset with respect to the docking marker */
    @SerialName(value = "orientation_offset") val orientationOffset: kotlin.Float? = null,

    /* The global id refering to the position that this offset belongs to */
    @SerialName(value = "pos_id") val posId: kotlin.String? = null,

    /* The url to the position */
    @SerialName(value = "position") val position: kotlin.String? = null,

    /* The x-offset with respect to the docking marker */
    @SerialName(value = "x_offset") val xOffset: kotlin.Float? = null,

    /* The y-offset with respect to the docking marker */
    @SerialName(value = "y_offset") val yOffset: kotlin.Float? = null

)

