/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param braked Whether the brake of the hook is active or not
 * @param state The state of the hook brake in machine format
 * @param stateString The state of the hook brake in human format
 */
@Serializable@Serializable

data class GetHookBrake (

    /* Whether the brake of the hook is active or not */
    @SerialName(value = "braked") val braked: kotlin.Boolean? = null,

    /* The state of the hook brake in machine format */
    @SerialName(value = "state") val state: kotlin.Long? = null,

    /* The state of the hook brake in human format */
    @SerialName(value = "state_string") val stateString: kotlin.String? = null

)

