/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param closed Whether the gripper of the hook is closed or not
 * @param state The sate of the hook gripper in machine format
 * @param stateString The state of the hook gripper in human format
 */
@Serializable@Serializable

data class GetHookGripper (

    /* Whether the gripper of the hook is closed or not */
    @SerialName(value = "closed") val closed: kotlin.Boolean? = null,

    /* The sate of the hook gripper in machine format */
    @SerialName(value = "state") val state: kotlin.Long? = null,

    /* The state of the hook gripper in human format */
    @SerialName(value = "state_string") val stateString: kotlin.String? = null

)

