/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param height The height of the hook in mm
 * @param state The state of the hook actuator in machine format
 * @param stateString The state of the hook actuator in human format
 */
@Serializable@Serializable

data class GetHookHeight (

    /* The height of the hook in mm */
    @SerialName(value = "height") val height: kotlin.Long? = null,

    /* The state of the hook actuator in machine format */
    @SerialName(value = "state") val state: kotlin.Long? = null,

    /* The state of the hook actuator in human format */
    @SerialName(value = "state_string") val stateString: kotlin.String? = null

)

