/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models

import com.federicogiordano.mirage.models.Brake
import com.federicogiordano.mirage.models.Gripper
import com.federicogiordano.mirage.models.Height

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param angle The angle of the hook arm
 * @param available Whether the hook data is available or not
 * @param brake 
 * @param gripper 
 * @param height 
 * @param qrMarkerName The name of the last seen qr marker
 */
@Serializable@Serializable

data class GetHook (

    /* The angle of the hook arm */
    @SerialName(value = "angle") val angle: kotlin.Float? = null,

    /* Whether the hook data is available or not */
    @SerialName(value = "available") val available: kotlin.Boolean? = null,

    @SerialName(value = "brake") val brake: Brake? = null,

    @SerialName(value = "gripper") val gripper: Gripper? = null,

    @SerialName(value = "height") val height: Height? = null,

    /* The name of the last seen qr marker */
    @SerialName(value = "qr_marker_name") val qrMarkerName: kotlin.String? = null

)

