/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param guid The global id unique across robots that identifies this position
 * @param map The url to the map this position belongs to
 * @param name The name of the position
 * @param typeId The type of position. see the general description above
 * @param url The URL of the resource
 */
@Serializable@Serializable

data class GetHelperPositions (

    /* The global id unique across robots that identifies this position */
    @SerialName(value = "guid") val guid: kotlin.String? = null,

    /* The url to the map this position belongs to */
    @SerialName(value = "map") val map: kotlin.String? = null,

    /* The name of the position */
    @SerialName(value = "name") val name: kotlin.String? = null,

    /* The type of position. see the general description above */
    @SerialName(value = "type_id") val typeId: kotlin.Long? = null,

    /* The URL of the resource */
    @SerialName(value = "url") val url: kotlin.String? = null

)

