/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param guid The global unique id across robots that identifies this io module
 * @param name The name of the io module
 * @param type The type of the io module. currently supported devices [bluetooth, wise].
 * @param url The URL of the resource
 */
@Serializable@Serializable

data class GetIoModules (

    /* The global unique id across robots that identifies this io module */
    @SerialName(value = "guid") val guid: kotlin.String? = null,

    /* The name of the io module */
    @SerialName(value = "name") val name: kotlin.String? = null,

    /* The type of the io module. currently supported devices [bluetooth, wise]. */
    @SerialName(value = "type") val type: kotlin.String? = null,

    /* The URL of the resource */
    @SerialName(value = "url") val url: kotlin.String? = null

)

