/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param address The address for connecting to the device. it can be a mac address or an ip depending on the type of io module
 * @param createdBy The url to the description of the type of this io module
 * @param createdById The global id of the user who created this entry
 * @param guid The global unique id across robots that identifies this io module
 * @param name The name of the io module
 * @param numInputs The number of inputs that the io module has
 * @param numOutputs The number or outputs that the io module has
 * @param type The type of the io module. currently supported devices [bluetooth, wise].
 */
@Serializable@Serializable

data class GetIoModule (

    /* The address for connecting to the device. it can be a mac address or an ip depending on the type of io module */
    @SerialName(value = "address") val address: kotlin.String? = null,

    /* The url to the description of the type of this io module */
    @SerialName(value = "created_by") val createdBy: kotlin.String? = null,

    /* The global id of the user who created this entry */
    @SerialName(value = "created_by_id") val createdById: kotlin.String? = null,

    /* The global unique id across robots that identifies this io module */
    @SerialName(value = "guid") val guid: kotlin.String? = null,

    /* The name of the io module */
    @SerialName(value = "name") val name: kotlin.String? = null,

    /* The number of inputs that the io module has */
    @SerialName(value = "num_inputs") val numInputs: kotlin.Long? = null,

    /* The number or outputs that the io module has */
    @SerialName(value = "num_outputs") val numOutputs: kotlin.Long? = null,

    /* The type of the io module. currently supported devices [bluetooth, wise]. */
    @SerialName(value = "type") val type: kotlin.String? = null

)

