/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param actionType The id of the type of action
 * @param guid The global id unique across robots that identifies this mission
 * @param missionId The id of the mission the action belongs to
 * @param parameters 
 * @param priority The priority of the action
 * @param url The URL of the resource
 */
@Serializable@Serializable

data class GetMissionActions (

    /* The id of the type of action */
    @SerialName(value = "action_type") val actionType: kotlin.String? = null,

    /* The global id unique across robots that identifies this mission */
    @SerialName(value = "guid") val guid: kotlin.String? = null,

    /* The id of the mission the action belongs to */
    @SerialName(value = "mission_id") val missionId: kotlin.String? = null,

    @SerialName(value = "parameters") val parameters: kotlin.collections.List<kotlin.String>? = null,

    /* The priority of the action */
    @SerialName(value = "priority") val priority: kotlin.Long? = null,

    /* The URL of the resource */
    @SerialName(value = "url") val url: kotlin.String? = null

)

