/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param actionId The id of the action
 * @param actionType The name of the action
 * @param finished The date and time when the action finished
 * @param id The id of the action
 * @param message The possible message produced by the action
 * @param missionQueueId The id of the action
 * @param parameters The list of parameters to the action
 * @param started The date and time when the action was started
 * @param state The end state after executing the action
 * @param url 
 */
@Serializable@Serializable

data class GetMissionQueueAction (

    /* The id of the action */
    @SerialName(value = "action_id") val actionId: kotlin.String? = null,

    /* The name of the action */
    @SerialName(value = "action_type") val actionType: kotlin.String? = null,

    /* The date and time when the action finished */
    @SerialName(value = "finished") val finished: kotlin.String? = null,

    /* The id of the action */
    @SerialName(value = "id") val id: kotlin.Long? = null,

    /* The possible message produced by the action */
    @SerialName(value = "message") val message: kotlin.String? = null,

    /* The id of the action */
    @SerialName(value = "mission_queue_id") val missionQueueId: kotlin.Long? = null,

    /* The list of parameters to the action */
    @SerialName(value = "parameters") val parameters: kotlin.collections.List<kotlin.String>? = null,

    /* The date and time when the action was started */
    @SerialName(value = "started") val started: kotlin.String? = null,

    /* The end state after executing the action */
    @SerialName(value = "state") val state: kotlin.String? = null,

    @SerialName(value = "url") val url: kotlin.String? = null

)

