/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param actions The url to the list of actions contained in this mission
 * @param createdBy The url to the description of the type of this position
 * @param createdById The global id of the user who created this entry
 * @param definition The url to the list of input parameters this mission accepts
 * @param description The description of the mission
 * @param groupId The id of the area this mission belongs to, or null if the mission belongs to all areas
 * @param guid The global id unique across robots that identifies this mission
 * @param hasUserParameters Indicates if the mission has dynamic parameters
 * @param hidden If this mission is hidden in the mission list
 * @param name The name of the mission
 * @param sessionId The id of the area this mission belongs to, or null if the mission belongs to all areas
 * @param valid Indicates if the mission contains only existing submissions
 */
@Serializable@Serializable

data class GetMission (

    /* The url to the list of actions contained in this mission */
    @SerialName(value = "actions") val actions: kotlin.String? = null,

    /* The url to the description of the type of this position */
    @SerialName(value = "created_by") val createdBy: kotlin.String? = null,

    /* The global id of the user who created this entry */
    @SerialName(value = "created_by_id") val createdById: kotlin.String? = null,

    /* The url to the list of input parameters this mission accepts */
    @SerialName(value = "definition") val definition: kotlin.String? = null,

    /* The description of the mission */
    @SerialName(value = "description") val description: kotlin.String? = null,

    /* The id of the area this mission belongs to, or null if the mission belongs to all areas */
    @SerialName(value = "group_id") val groupId: kotlin.String? = null,

    /* The global id unique across robots that identifies this mission */
    @SerialName(value = "guid") val guid: kotlin.String? = null,

    /* Indicates if the mission has dynamic parameters */
    @SerialName(value = "has_user_parameters") val hasUserParameters: kotlin.Boolean? = null,

    /* If this mission is hidden in the mission list */
    @SerialName(value = "hidden") val hidden: kotlin.Boolean? = null,

    /* The name of the mission */
    @SerialName(value = "name") val name: kotlin.String? = null,

    /* The id of the area this mission belongs to, or null if the mission belongs to all areas */
    @SerialName(value = "session_id") val sessionId: kotlin.String? = null,

    /* Indicates if the mission contains only existing submissions */
    @SerialName(value = "valid") val valid: kotlin.Boolean? = null

)

