/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param actionType 
 * @param name 
 * @param url The URL of the resource
 */
@Serializable@Serializable

data class GetMissionDefinition (

    @SerialName(value = "action_type") val actionType: kotlin.String? = null,

    @SerialName(value = "name") val name: kotlin.String? = null,

    /* The URL of the resource */
    @SerialName(value = "url") val url: kotlin.String? = null

)

