/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param createdBy The url to the description of the type of this position
 * @param createdById The global id of the user who created this entry
 * @param feature The name of the position
 * @param guid The global id unique across robots that identifies this position
 * @param icon The name of the position
 * @param name The name of the position
 * @param priority The name of the position
 */
@Serializable@Serializable

data class GetMissionGroup (

    /* The url to the description of the type of this position */
    @SerialName(value = "created_by") val createdBy: kotlin.String? = null,

    /* The global id of the user who created this entry */
    @SerialName(value = "created_by_id") val createdById: kotlin.String? = null,

    /* The name of the position */
    @SerialName(value = "feature") val feature: kotlin.String? = null,

    /* The global id unique across robots that identifies this position */
    @SerialName(value = "guid") val guid: kotlin.String? = null,

    /* The name of the position */
    @SerialName(value = "icon") val icon: com.federicogiordano.mirage.infrastructure.Base64ByteArray? = null,

    /* The name of the position */
    @SerialName(value = "name") val name: kotlin.String? = null,

    /* The name of the position */
    @SerialName(value = "priority") val priority: kotlin.Long? = null

)

