/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param goalPos The url to the end position of the path
 * @param guid The global id unique across robots that identifies this path
 * @param startPos The url to the start position of the path
 * @param url The URL of the resource
 */
@Serializable@Serializable

data class GetMapPaths (

    /* The url to the end position of the path */
    @SerialName(value = "goal_pos") val goalPos: kotlin.String? = null,

    /* The global id unique across robots that identifies this path */
    @SerialName(value = "guid") val guid: kotlin.String? = null,

    /* The url to the start position of the path */
    @SerialName(value = "start_pos") val startPos: kotlin.String? = null,

    /* The URL of the resource */
    @SerialName(value = "url") val url: kotlin.String? = null

)

