/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param actions The list of parameters this mission queue entry accepts
 * @param controlPosid Global id of position used during control states
 * @param controlState Mission control state. a value above zero indicates that the robot needs an external input in order to continue
 * @param createdBy The url to the description of the type of this element
 * @param createdById The global id of the user who created this entry
 * @param description Inerited from mission description, when item was queued
 * @param finished The date and time when the mission was finished
 * @param id The id of the mission queue entry
 * @param message The last message produced by the actions in the mission list
 * @param mission The url to the mission that mission that was executed
 * @param missionId The global id of the mission that was executed
 * @param ordered The date end time when the mission was queued
 * @param parameters 
 * @param priority The id of the action
 * @param started The date and time when the missin was started
 * @param state The end state after the mission was executed
 */
@Serializable@Serializable

data class GetMissionQueue (

    /* The list of parameters this mission queue entry accepts */
    @SerialName(value = "actions") val actions: kotlin.String? = null,

    /* Global id of position used during control states */
    @SerialName(value = "control_posid") val controlPosid: kotlin.String? = null,

    /* Mission control state. a value above zero indicates that the robot needs an external input in order to continue */
    @SerialName(value = "control_state") val controlState: kotlin.Long? = null,

    /* The url to the description of the type of this element */
    @SerialName(value = "created_by") val createdBy: kotlin.String? = null,

    /* The global id of the user who created this entry */
    @SerialName(value = "created_by_id") val createdById: kotlin.String? = null,

    /* Inerited from mission description, when item was queued */
    @SerialName(value = "description") val description: kotlin.String? = null,

    /* The date and time when the mission was finished */
    @SerialName(value = "finished") val finished: kotlin.String? = null,

    /* The id of the mission queue entry */
    @SerialName(value = "id") val id: kotlin.Long? = null,

    /* The last message produced by the actions in the mission list */
    @SerialName(value = "message") val message: kotlin.String? = null,

    /* The url to the mission that mission that was executed */
    @SerialName(value = "mission") val mission: kotlin.String? = null,

    /* The global id of the mission that was executed */
    @SerialName(value = "mission_id") val missionId: kotlin.String? = null,

    /* The date end time when the mission was queued */
    @SerialName(value = "ordered") val ordered: kotlin.String? = null,

    @SerialName(value = "parameters") val parameters: kotlin.collections.List<kotlin.String>? = null,

    /* The id of the action */
    @SerialName(value = "priority") val priority: kotlin.Long? = null,

    /* The date and time when the missin was started */
    @SerialName(value = "started") val started: kotlin.String? = null,

    /* The end state after the mission was executed */
    @SerialName(value = "state") val state: kotlin.String? = null

)

