/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param coilId The id of the coil to trigger the mission
 * @param guid The global id unique across robots that identifies this modbus mission
 * @param url The URL of the resource
 */
@Serializable@Serializable

data class GetModbusMissions (

    /* The id of the coil to trigger the mission */
    @SerialName(value = "coil_id") val coilId: kotlin.Long? = null,

    /* The global id unique across robots that identifies this modbus mission */
    @SerialName(value = "guid") val guid: kotlin.String? = null,

    /* The URL of the resource */
    @SerialName(value = "url") val url: kotlin.String? = null

)

