/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param dataType The data type needed
 * @param description A more detailed explanation of the attribute
 * @param id The id of the modbus entry
 * @param permissions If it is allowed to read or write this element
 * @param registers The registers on the plc where the data will be stored
 * @param title A textual description of the desired element
 * @param type The endpoint to which the element refers
 */
@Serializable@Serializable

data class GetModbus (

    /* The data type needed */
    @SerialName(value = "data_type") val dataType: kotlin.String? = null,

    /* A more detailed explanation of the attribute */
    @SerialName(value = "description") val description: kotlin.String? = null,

    /* The id of the modbus entry */
    @SerialName(value = "id") val id: kotlin.Long? = null,

    /* If it is allowed to read or write this element */
    @SerialName(value = "permissions") val permissions: kotlin.String? = null,

    /* The registers on the plc where the data will be stored */
    @SerialName(value = "registers") val registers: kotlin.collections.List<kotlin.String>? = null,

    /* A textual description of the desired element */
    @SerialName(value = "title") val title: kotlin.String? = null,

    /* The endpoint to which the element refers */
    @SerialName(value = "type") val type: kotlin.String? = null

)

