/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id The id of the mission queue entry
 * @param state The end state after the mission was executed
 * @param url The URL of the resource
 */
@Serializable@Serializable

data class GetMissionQueues (

    /* The id of the mission queue entry */
    @SerialName(value = "id") val id: kotlin.Long? = null,

    /* The end state after the mission was executed */
    @SerialName(value = "state") val state: kotlin.String? = null,

    /* The URL of the resource */
    @SerialName(value = "url") val url: kotlin.String? = null

)

