/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param guid The global unique id across robots that identifies this user
 * @param name The name of the user
 * @param url The URL of the resource
 * @param userGroup Url for the user group this user is in
 * @param userGroupId Global id of the user group this user is in
 */
@Serializable@Serializable

data class GetMe (

    /* The global unique id across robots that identifies this user */
    @SerialName(value = "guid") val guid: kotlin.String? = null,

    /* The name of the user */
    @SerialName(value = "name") val name: kotlin.String? = null,

    /* The URL of the resource */
    @SerialName(value = "url") val url: kotlin.String? = null,

    /* Url for the user group this user is in */
    @SerialName(value = "user_group") val userGroup: kotlin.String? = null,

    /* Global id of the user group this user is in */
    @SerialName(value = "user_group_id") val userGroupId: kotlin.String? = null

)

