/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param coilId The id of the coil to trigger the mission
 * @param createdBy The url to the description of the type of this modbus mission
 * @param createdById The global id of the user who created this entry
 * @param guid The global id unique across robots that identifies this modbus mission
 * @param id The id of the modbus mission entry
 * @param mission The url to the mission details
 * @param missionId The global id of the mission that was executed
 * @param name A more detailed explanation of the attribute
 * @param parameters 
 */
@Serializable@Serializable

data class GetModbusMission (

    /* The id of the coil to trigger the mission */
    @SerialName(value = "coil_id") val coilId: kotlin.Long? = null,

    /* The url to the description of the type of this modbus mission */
    @SerialName(value = "created_by") val createdBy: kotlin.String? = null,

    /* The global id of the user who created this entry */
    @SerialName(value = "created_by_id") val createdById: kotlin.String? = null,

    /* The global id unique across robots that identifies this modbus mission */
    @SerialName(value = "guid") val guid: kotlin.String? = null,

    /* The id of the modbus mission entry */
    @SerialName(value = "id") val id: kotlin.Long? = null,

    /* The url to the mission details */
    @SerialName(value = "mission") val mission: kotlin.String? = null,

    /* The global id of the mission that was executed */
    @SerialName(value = "mission_id") val missionId: kotlin.String? = null,

    /* A more detailed explanation of the attribute */
    @SerialName(value = "name") val name: kotlin.String? = null,

    @SerialName(value = "parameters") val parameters: kotlin.collections.List<kotlin.String>? = null

)

