/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param createdBy The url to the description of the type of this position
 * @param createdById The global id of the user who created this entry
 * @param guid The global id unique across robots that identifies this map
 * @param map If this map is navigation map or not
 * @param metadata If this map is a web map or not
 * @param name The name of the map
 * @param oneWayMap If this map is navigation map or not
 * @param originTheta The angle in the map of the center of the map relative to the robots position
 * @param originX The x-coordinate in the map of the center of the map relative to the robots position
 * @param originY The y-coordinate in the map of the center of the map relative to the robots position
 * @param pathGuides The url to the list of path guides in this map
 * @param paths The url to the list of paths in this map
 * @param positions The url to the list of positions in this map
 * @param resolution The resolution of the map
 * @param sessionId The global id unique across robots of the area containing this map
 */
@Serializable@Serializable

data class GetMap (

    /* The url to the description of the type of this position */
    @SerialName(value = "created_by") val createdBy: kotlin.String? = null,

    /* The global id of the user who created this entry */
    @SerialName(value = "created_by_id") val createdById: kotlin.String? = null,

    /* The global id unique across robots that identifies this map */
    @SerialName(value = "guid") val guid: kotlin.String? = null,

    /* If this map is navigation map or not */
    @SerialName(value = "map") val map: com.federicogiordano.mirage.infrastructure.Base64ByteArray? = null,

    /* If this map is a web map or not */
    @SerialName(value = "metadata") val metadata: com.federicogiordano.mirage.infrastructure.Base64ByteArray? = null,

    /* The name of the map */
    @SerialName(value = "name") val name: kotlin.String? = null,

    /* If this map is navigation map or not */
    @SerialName(value = "one_way_map") val oneWayMap: com.federicogiordano.mirage.infrastructure.Base64ByteArray? = null,

    /* The angle in the map of the center of the map relative to the robots position */
    @SerialName(value = "origin_theta") val originTheta: kotlin.Float? = null,

    /* The x-coordinate in the map of the center of the map relative to the robots position */
    @SerialName(value = "origin_x") val originX: kotlin.Float? = null,

    /* The y-coordinate in the map of the center of the map relative to the robots position */
    @SerialName(value = "origin_y") val originY: kotlin.Float? = null,

    /* The url to the list of path guides in this map */
    @SerialName(value = "path_guides") val pathGuides: kotlin.String? = null,

    /* The url to the list of paths in this map */
    @SerialName(value = "paths") val paths: kotlin.String? = null,

    /* The url to the list of positions in this map */
    @SerialName(value = "positions") val positions: kotlin.String? = null,

    /* The resolution of the map */
    @SerialName(value = "resolution") val resolution: kotlin.Float? = null,

    /* The global id unique across robots of the area containing this map */
    @SerialName(value = "session_id") val sessionId: kotlin.String? = null

)

