/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param createdBy The url to the description of the type of this position
 * @param createdById The global id of the user who created this entry
 * @param goalPosId The id of the end position for the transition list
 * @param guid The global id unique across robots that identifies this path
 * @param missionId The guid of the mission in the transition list
 * @param startPosId The id of the start position for the transition list
 */
@Serializable@Serializable

data class GetPositionTransitionListFromSession (

    /* The url to the description of the type of this position */
    @SerialName(value = "created_by") val createdBy: kotlin.String? = null,

    /* The global id of the user who created this entry */
    @SerialName(value = "created_by_id") val createdById: kotlin.String? = null,

    /* The id of the end position for the transition list */
    @SerialName(value = "goal_pos_id") val goalPosId: kotlin.String? = null,

    /* The global id unique across robots that identifies this path */
    @SerialName(value = "guid") val guid: kotlin.String? = null,

    /* The guid of the mission in the transition list */
    @SerialName(value = "mission_id") val missionId: kotlin.String? = null,

    /* The id of the start position for the transition list */
    @SerialName(value = "start_pos_id") val startPosId: kotlin.String? = null

)

