/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param createdBy The url to the description of the type of this position
 * @param createdById The global id of the user who created this entry
 * @param dockingOffsets The url to the possible docking offset. if the position does not have a docking offset then this field is empty
 * @param guid The global id unique across robots that identifies this position
 * @param helpPositions 
 * @param map The url to the map this position belongs to
 * @param mapId The global id of the map this positions belongs to
 * @param name The name of the position
 * @param orientation The orientation of the position in degrees relative to origo of the underlying map
 * @param parent The url to the possible parent position. if the position does not have a parent position then this field is empty
 * @param parentId The global id of the possible parent position of the current position. a parent position is a position related to the current position, for instance the parent position of a trolley left entry position is the actual trolley position. if the position does not have a parent position then this field is empty
 * @param posX The x-coordinate of the position relative to origo of the underlying map
 * @param posY The y-coordinate of the position relative to origo of the underlying map
 * @param type The url to the description of the type of this position
 * @param typeId The type of position. see the general description above
 */
@Serializable@Serializable

data class GetPosition (

    /* The url to the description of the type of this position */
    @SerialName(value = "created_by") val createdBy: kotlin.String? = null,

    /* The global id of the user who created this entry */
    @SerialName(value = "created_by_id") val createdById: kotlin.String? = null,

    /* The url to the possible docking offset. if the position does not have a docking offset then this field is empty */
    @SerialName(value = "docking_offsets") val dockingOffsets: kotlin.String? = null,

    /* The global id unique across robots that identifies this position */
    @SerialName(value = "guid") val guid: kotlin.String? = null,

    @SerialName(value = "help_positions") val helpPositions: kotlin.String? = null,

    /* The url to the map this position belongs to */
    @SerialName(value = "map") val map: kotlin.String? = null,

    /* The global id of the map this positions belongs to */
    @SerialName(value = "map_id") val mapId: kotlin.String? = null,

    /* The name of the position */
    @SerialName(value = "name") val name: kotlin.String? = null,

    /* The orientation of the position in degrees relative to origo of the underlying map */
    @SerialName(value = "orientation") val orientation: kotlin.Float? = null,

    /* The url to the possible parent position. if the position does not have a parent position then this field is empty */
    @SerialName(value = "parent") val parent: kotlin.String? = null,

    /* The global id of the possible parent position of the current position. a parent position is a position related to the current position, for instance the parent position of a trolley left entry position is the actual trolley position. if the position does not have a parent position then this field is empty */
    @SerialName(value = "parent_id") val parentId: kotlin.String? = null,

    /* The x-coordinate of the position relative to origo of the underlying map */
    @SerialName(value = "pos_x") val posX: kotlin.Float? = null,

    /* The y-coordinate of the position relative to origo of the underlying map */
    @SerialName(value = "pos_y") val posY: kotlin.Float? = null,

    /* The url to the description of the type of this position */
    @SerialName(value = "type") val type: kotlin.String? = null,

    /* The type of position. see the general description above */
    @SerialName(value = "type_id") val typeId: kotlin.Long? = null

)

