/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param active Boolean indicating if a path guide precalculation is in progress
 * @param failCount The number of paths that was not possible to precalculate
 * @param message Status message from the precalculation module
 * @param pathGuideGuid The global unique id across robots that identifies the path guide being precalculated
 * @param successCount The number of paths that has been successfully calculated
 * @param totalCount The number of total paths to calculate
 */
@Serializable@Serializable

data class GetPathGuidesPrecalc (

    /* Boolean indicating if a path guide precalculation is in progress */
    @SerialName(value = "active") val active: kotlin.Boolean? = null,

    /* The number of paths that was not possible to precalculate */
    @SerialName(value = "fail_count") val failCount: kotlin.Long? = null,

    /* Status message from the precalculation module */
    @SerialName(value = "message") val message: kotlin.String? = null,

    /* The global unique id across robots that identifies the path guide being precalculated */
    @SerialName(value = "path_guide_guid") val pathGuideGuid: kotlin.String? = null,

    /* The number of paths that has been successfully calculated */
    @SerialName(value = "success_count") val successCount: kotlin.Long? = null,

    /* The number of total paths to calculate */
    @SerialName(value = "total_count") val totalCount: kotlin.Long? = null

)

