/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param createdBy The url to the description of the type of this element
 * @param createdById The global unique id of the user that created this path guide
 * @param goalsCount The number of goal positions in the path guide
 * @param guid The global unique id across robots that identifies this path guide
 * @param mapId The global id of the map this path guide belongs to
 * @param name The name of the path guide
 * @param options The url to the list of position options for this path path
 * @param positions The url to the list of positions used in this path guide
 * @param startsCount The number of start positions in the path guide
 * @param viasCount The number of via positions in the path guide
 */
@Serializable@Serializable

data class GetPathGuide (

    /* The url to the description of the type of this element */
    @SerialName(value = "created_by") val createdBy: kotlin.String? = null,

    /* The global unique id of the user that created this path guide */
    @SerialName(value = "created_by_id") val createdById: kotlin.String? = null,

    /* The number of goal positions in the path guide */
    @SerialName(value = "goals_count") val goalsCount: kotlin.Long? = null,

    /* The global unique id across robots that identifies this path guide */
    @SerialName(value = "guid") val guid: kotlin.String? = null,

    /* The global id of the map this path guide belongs to */
    @SerialName(value = "map_id") val mapId: kotlin.String? = null,

    /* The name of the path guide */
    @SerialName(value = "name") val name: kotlin.String? = null,

    /* The url to the list of position options for this path path */
    @SerialName(value = "options") val options: kotlin.String? = null,

    /* The url to the list of positions used in this path guide */
    @SerialName(value = "positions") val positions: kotlin.String? = null,

    /* The number of start positions in the path guide */
    @SerialName(value = "starts_count") val startsCount: kotlin.Long? = null,

    /* The number of via positions in the path guide */
    @SerialName(value = "vias_count") val viasCount: kotlin.Long? = null

)

