/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param hidden False if the position is not created by the user
 * @param id Unique id for the position type
 * @param name Name of the position type
 * @param reachableForRobot True if the robot can actually go to that position
 */
@Serializable@Serializable

data class GetPositionType (

    /* False if the position is not created by the user */
    @SerialName(value = "hidden") val hidden: kotlin.Boolean? = null,

    /* Unique id for the position type */
    @SerialName(value = "id") val id: kotlin.Long? = null,

    /* Name of the position type */
    @SerialName(value = "name") val name: kotlin.String? = null,

    /* True if the robot can actually go to that position */
    @SerialName(value = "reachable_for_robot") val reachableForRobot: kotlin.Boolean? = null

)

