/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param autogenerated If the path was autogenerated or not
 * @param footprint The footprint of the robot for which this path was generated
 * @param goalPos The url to the end position of the path
 * @param goalPosId The id of the end position of the path
 * @param guid The global id unique across robots that identifies this path
 * @param lastUsed The date and time of the last time this path was used
 * @param length The length of the path in meters
 * @param mapCrc The crc for the path
 * @param path A binary representation of the path
 * @param startPos The url to the start position of the path
 * @param startPosId The id of the start position of the path
 * @param time The time it took to drive the path the first time
 * @param valid If the path is valid or not
 */
@Serializable@Serializable

data class GetPath (

    /* If the path was autogenerated or not */
    @SerialName(value = "autogenerated") val autogenerated: kotlin.Boolean? = null,

    /* The footprint of the robot for which this path was generated */
    @SerialName(value = "footprint") val footprint: kotlin.String? = null,

    /* The url to the end position of the path */
    @SerialName(value = "goal_pos") val goalPos: kotlin.String? = null,

    /* The id of the end position of the path */
    @SerialName(value = "goal_pos_id") val goalPosId: kotlin.String? = null,

    /* The global id unique across robots that identifies this path */
    @SerialName(value = "guid") val guid: kotlin.String? = null,

    /* The date and time of the last time this path was used */
    @SerialName(value = "last_used") val lastUsed: kotlin.String? = null,

    /* The length of the path in meters */
    @SerialName(value = "length") val length: kotlin.Float? = null,

    /* The crc for the path */
    @SerialName(value = "map_crc") val mapCrc: kotlin.String? = null,

    /* A binary representation of the path */
    @SerialName(value = "path") val path: com.federicogiordano.mirage.infrastructure.Base64ByteArray? = null,

    /* The url to the start position of the path */
    @SerialName(value = "start_pos") val startPos: kotlin.String? = null,

    /* The id of the start position of the path */
    @SerialName(value = "start_pos_id") val startPosId: kotlin.String? = null,

    /* The time it took to drive the path the first time */
    @SerialName(value = "time") val time: kotlin.Float? = null,

    /* If the path is valid or not */
    @SerialName(value = "valid") val valid: kotlin.Boolean? = null

)

