/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models

import com.federicogiordano.mirage.models.Goals
import com.federicogiordano.mirage.models.Starts
import com.federicogiordano.mirage.models.Vias

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param goals The list of options for goal positions
 * @param starts The list of options for start positions
 * @param vias The list of options for via positions
 */
@Serializable@Serializable

data class GetPathGuideOptions (

    /* The list of options for goal positions */
    @SerialName(value = "goals") val goals: kotlin.collections.List<Goals>? = null,

    /* The list of options for start positions */
    @SerialName(value = "starts") val starts: kotlin.collections.List<Starts>? = null,

    /* The list of options for via positions */
    @SerialName(value = "vias") val vias: kotlin.collections.List<Vias>? = null

)

