/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id The index of the register
 * @param label A label for the register
 * @param `value` The value of the register
 */
@Serializable@Serializable

data class GetRegister (

    /* The index of the register */
    @SerialName(value = "id") val id: kotlin.Long? = null,

    /* A label for the register */
    @SerialName(value = "label") val label: kotlin.String? = null,

    /* The value of the register */
    @SerialName(value = "value") val `value`: kotlin.Float? = null

)

