/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param default 
 * @param id 
 * @param name 
 * @param parentName 
 * @param url The URL of the resource
 * @param `value` 
 */
@Serializable@Serializable

data class GetSettingGroupSettings (

    @SerialName(value = "default") val default: kotlin.String? = null,

    @SerialName(value = "id") val id: kotlin.Long? = null,

    @SerialName(value = "name") val name: kotlin.String? = null,

    @SerialName(value = "parent_name") val parentName: kotlin.String? = null,

    /* The URL of the resource */
    @SerialName(value = "url") val url: kotlin.String? = null,

    @SerialName(value = "value") val `value`: kotlin.String? = null

)

