/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param guid The guid of the software upgrade
 * @param uploadDate The upload date of the software upgrade
 * @param version The version of the software upgrade
 */
@Serializable@Serializable

data class GetSoftwareUpgrade (

    /* The guid of the software upgrade */
    @SerialName(value = "guid") val guid: kotlin.String? = null,

    /* The upload date of the software upgrade */
    @SerialName(value = "upload_date") val uploadDate: kotlin.String? = null,

    /* The version of the software upgrade */
    @SerialName(value = "version") val version: kotlin.String? = null

)

