/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param advancedSettingsCount 
 * @param description 
 * @param id 
 * @param name 
 * @param priority 
 * @param settingsCount 
 */
@Serializable@Serializable

data class GetSettingGroup (

    @SerialName(value = "advanced_settings_count") val advancedSettingsCount: kotlin.Long? = null,

    @SerialName(value = "description") val description: kotlin.String? = null,

    @SerialName(value = "id") val id: kotlin.Long? = null,

    @SerialName(value = "name") val name: kotlin.String? = null,

    @SerialName(value = "priority") val priority: kotlin.Long? = null,

    @SerialName(value = "settings_count") val settingsCount: kotlin.Long? = null

)

