/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param createdAt Creation time of the service note
 * @param createdBy The url to the user
 * @param createdById The user which created the log
 * @param createdByName The user name which created the log
 * @param description The sevice note
 * @param guid The global unique id across robots that identifies this service note
 * @param ownerGroup The url to the owner group
 * @param ownerGroupGuid The usergroup which owns the service book
 * @param ownerGroupName The group name which owns the log
 */
@Serializable@Serializable

data class GetServiceBooks (

    /* Creation time of the service note */
    @SerialName(value = "created_at") val createdAt: kotlin.String? = null,

    /* The url to the user */
    @SerialName(value = "created_by") val createdBy: kotlin.String? = null,

    /* The user which created the log */
    @SerialName(value = "created_by_id") val createdById: kotlin.String? = null,

    /* The user name which created the log */
    @SerialName(value = "created_by_name") val createdByName: kotlin.String? = null,

    /* The sevice note */
    @SerialName(value = "description") val description: kotlin.String? = null,

    /* The global unique id across robots that identifies this service note */
    @SerialName(value = "guid") val guid: kotlin.String? = null,

    /* The url to the owner group */
    @SerialName(value = "owner_group") val ownerGroup: kotlin.String? = null,

    /* The usergroup which owns the service book */
    @SerialName(value = "owner_group_guid") val ownerGroupGuid: kotlin.String? = null,

    /* The group name which owns the log */
    @SerialName(value = "owner_group_name") val ownerGroupName: kotlin.String? = null

)

