/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param guid The global id unique across robots that identifies this sound
 * @param length The length of the sound in the format hh:mm:ss
 * @param name The name of the sound
 * @param url The URL of the resource
 * @param volume The volumne of the sound when played
 */
@Serializable@Serializable

data class GetSoundStream (

    /* The global id unique across robots that identifies this sound */
    @SerialName(value = "guid") val guid: kotlin.String? = null,

    /* The length of the sound in the format hh:mm:ss */
    @SerialName(value = "length") val length: kotlin.String? = null,

    /* The name of the sound */
    @SerialName(value = "name") val name: kotlin.String? = null,

    /* The URL of the resource */
    @SerialName(value = "url") val url: kotlin.String? = null,

    /* The volumne of the sound when played */
    @SerialName(value = "volume") val volume: kotlin.Long? = null

)

