/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param date The date where the backup was created
 * @param guid The guid of the software backup
 * @param state The state of the software backup
 * @param version The version of the software backup
 */
@Serializable@Serializable

data class GetSoftwareBackup (

    /* The date where the backup was created */
    @SerialName(value = "date") val date: kotlin.String? = null,

    /* The guid of the software backup */
    @SerialName(value = "guid") val guid: kotlin.String? = null,

    /* The state of the software backup */
    @SerialName(value = "state") val state: kotlin.String? = null,

    /* The version of the software backup */
    @SerialName(value = "version") val version: kotlin.String? = null

)

