/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param lock Lock applied
 * @param lockPending Lock pending
 * @param url The URL of the resource
 */
@Serializable@Serializable

data class GetSoftwareLockSelf (

    /* Lock applied */
    @SerialName(value = "lock") val lock: kotlin.Boolean? = null,

    /* Lock pending */
    @SerialName(value = "lock_pending") val lockPending: kotlin.Boolean? = null,

    /* The URL of the resource */
    @SerialName(value = "url") val url: kotlin.String? = null

)

