/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param active Boolean indicating whether the session is the active session in the fleet
 * @param createdBy The url to the description of the type of this position
 * @param createdById The global id of the user who created this entry
 * @param description A possible description of the area
 * @param export 
 * @param guid The global id unique across robots that identifies this area
 * @param maps The url to the list of maps that is in this area
 * @param name The name of the area
 */
@Serializable@Serializable

data class GetSession (

    /* Boolean indicating whether the session is the active session in the fleet */
    @SerialName(value = "active") val active: kotlin.Boolean? = null,

    /* The url to the description of the type of this position */
    @SerialName(value = "created_by") val createdBy: kotlin.String? = null,

    /* The global id of the user who created this entry */
    @SerialName(value = "created_by_id") val createdById: kotlin.String? = null,

    /* A possible description of the area */
    @SerialName(value = "description") val description: kotlin.String? = null,

    @SerialName(value = "export") val export: kotlin.String? = null,

    /* The global id unique across robots that identifies this area */
    @SerialName(value = "guid") val guid: kotlin.String? = null,

    /* The url to the list of maps that is in this area */
    @SerialName(value = "maps") val maps: kotlin.String? = null,

    /* The name of the area */
    @SerialName(value = "name") val name: kotlin.String? = null

)

