/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param action The action performed (upgrade/restore)
 * @param endTime The end time of the upgrade
 * @param from The software version upgrading from
 * @param guid The guid of upgrade entry
 * @param message The status message from upgrade
 * @param startTime The start time of the upgrade
 * @param state The state of the upgrade (succeeded/failed/started
 * @param to The software version upgrading to
 */
@Serializable@Serializable

data class GetSoftwareLog (

    /* The action performed (upgrade/restore) */
    @SerialName(value = "action") val action: kotlin.String? = null,

    /* The end time of the upgrade */
    @SerialName(value = "end_time") val endTime: kotlin.String? = null,

    /* The software version upgrading from */
    @SerialName(value = "from") val from: kotlin.String? = null,

    /* The guid of upgrade entry */
    @SerialName(value = "guid") val guid: kotlin.String? = null,

    /* The status message from upgrade */
    @SerialName(value = "message") val message: kotlin.String? = null,

    /* The start time of the upgrade */
    @SerialName(value = "start_time") val startTime: kotlin.String? = null,

    /* The state of the upgrade (succeeded/failed/started */
    @SerialName(value = "state") val state: kotlin.String? = null,

    /* The software version upgrading to */
    @SerialName(value = "to") val to: kotlin.String? = null

)

