/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param constraints 
 * @param default 
 * @param description 
 * @param fieldtype 
 * @param fullName 
 * @param id 
 * @param name 
 * @param parentId 
 * @param parentName 
 * @param parentValue 
 * @param selectGroup 
 * @param settingsGroup 
 * @param settingsGroupId 
 * @param type 
 * @param `value` 
 */
@Serializable@Serializable

data class GetSettingAdvanced (

    @SerialName(value = "constraints") val constraints: kotlin.String? = null,

    @SerialName(value = "default") val default: kotlin.String? = null,

    @SerialName(value = "description") val description: kotlin.String? = null,

    @SerialName(value = "fieldtype") val fieldtype: kotlin.String? = null,

    @SerialName(value = "full_name") val fullName: kotlin.String? = null,

    @SerialName(value = "id") val id: kotlin.Long? = null,

    @SerialName(value = "name") val name: kotlin.String? = null,

    @SerialName(value = "parent_id") val parentId: kotlin.String? = null,

    @SerialName(value = "parent_name") val parentName: kotlin.String? = null,

    @SerialName(value = "parent_value") val parentValue: kotlin.String? = null,

    @SerialName(value = "select_group") val selectGroup: kotlin.Long? = null,

    @SerialName(value = "settings_group") val settingsGroup: kotlin.String? = null,

    @SerialName(value = "settings_group_id") val settingsGroupId: kotlin.Long? = null,

    @SerialName(value = "type") val type: kotlin.String? = null,

    @SerialName(value = "value") val `value`: kotlin.String? = null

)

