/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param expirationTime 
 * @param ip 
 * @param loginTime 
 * @param token 
 * @param userId 
 */
@Serializable@Serializable

data class GetUsersAuth (

    @SerialName(value = "expiration_time") val expirationTime: kotlin.String? = null,

    @SerialName(value = "ip") val ip: kotlin.String? = null,

    @SerialName(value = "login_time") val loginTime: kotlin.String? = null,

    @SerialName(value = "token") val token: kotlin.String? = null,

    @SerialName(value = "user_id") val userId: kotlin.String? = null

)

