/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param createTime Creation time of the user
 * @param createdBy The url to the description of the type of this position
 * @param createdById The global id of the user who created this entry
 * @param dashboardId 
 * @param email The email of the user
 * @param guid The global unique id across robots that identifies this user
 * @param name The name of the user
 * @param singleDashboard 
 * @param updateTime Last time the user was updated
 * @param url Url to this user
 * @param userGroup Url for the user group this user is in
 * @param userGroupId Global id of the user group this user is in
 * @param username The username of the user
 */
@Serializable@Serializable

data class GetUser (

    /* Creation time of the user */
    @SerialName(value = "create_time") val createTime: kotlin.String? = null,

    /* The url to the description of the type of this position */
    @SerialName(value = "created_by") val createdBy: kotlin.String? = null,

    /* The global id of the user who created this entry */
    @SerialName(value = "created_by_id") val createdById: kotlin.String? = null,

    @SerialName(value = "dashboard_id") val dashboardId: kotlin.String? = null,

    /* The email of the user */
    @SerialName(value = "email") val email: kotlin.String? = null,

    /* The global unique id across robots that identifies this user */
    @SerialName(value = "guid") val guid: kotlin.String? = null,

    /* The name of the user */
    @SerialName(value = "name") val name: kotlin.String? = null,

    @SerialName(value = "single_dashboard") val singleDashboard: kotlin.Boolean? = null,

    /* Last time the user was updated */
    @SerialName(value = "update_time") val updateTime: kotlin.String? = null,

    /* Url to this user */
    @SerialName(value = "url") val url: kotlin.String? = null,

    /* Url for the user group this user is in */
    @SerialName(value = "user_group") val userGroup: kotlin.String? = null,

    /* Global id of the user group this user is in */
    @SerialName(value = "user_group_id") val userGroupId: kotlin.String? = null,

    /* The username of the user */
    @SerialName(value = "username") val username: kotlin.String? = null

)

