/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param createTime Creation time of the usergroup
 * @param createdBy The url to the description of the type of this position
 * @param createdById The global id of the user who created this entry
 * @param guid The global unique id across robots that identifies this usergroup
 * @param name Name of the usergroup
 * @param updateTime Last time the usergroup was updated
 */
@Serializable@Serializable

data class GetUserGroup (

    /* Creation time of the usergroup */
    @SerialName(value = "create_time") val createTime: kotlin.String? = null,

    /* The url to the description of the type of this position */
    @SerialName(value = "created_by") val createdBy: kotlin.String? = null,

    /* The global id of the user who created this entry */
    @SerialName(value = "created_by_id") val createdById: kotlin.String? = null,

    /* The global unique id across robots that identifies this usergroup */
    @SerialName(value = "guid") val guid: kotlin.String? = null,

    /* Name of the usergroup */
    @SerialName(value = "name") val name: kotlin.String? = null,

    /* Last time the usergroup was updated */
    @SerialName(value = "update_time") val updateTime: kotlin.String? = null

)

