/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param bssid Access point mac address
 * @param connected Connected to the network of this connection
 * @param mac Network adapter mac address
 * @param name Name or id of the connection
 * @param url The URL of the resource
 * @param uuid Uuid of the connection
 */
@Serializable@Serializable

data class GetWifiConnections (

    /* Access point mac address */
    @SerialName(value = "bssid") val bssid: kotlin.String? = null,

    /* Connected to the network of this connection */
    @SerialName(value = "connected") val connected: kotlin.Boolean? = null,

    /* Network adapter mac address */
    @SerialName(value = "mac") val mac: kotlin.String? = null,

    /* Name or id of the connection */
    @SerialName(value = "name") val name: kotlin.String? = null,

    /* The URL of the resource */
    @SerialName(value = "url") val url: kotlin.String? = null,

    /* Uuid of the connection */
    @SerialName(value = "uuid") val uuid: kotlin.String? = null

)

