/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param connected Connected to this network
 * @param guid The guid of the wifi
 * @param ssid Ssid of the wlan
 * @param url The URL of the resource
 */
@Serializable@Serializable

data class GetWifiNetworks (

    /* Connected to this network */
    @SerialName(value = "connected") val connected: kotlin.Boolean? = null,

    /* The guid of the wifi */
    @SerialName(value = "guid") val guid: kotlin.String? = null,

    /* Ssid of the wlan */
    @SerialName(value = "ssid") val ssid: kotlin.String? = null,

    /* The URL of the resource */
    @SerialName(value = "url") val url: kotlin.String? = null

)

