/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param channel Network channel
 * @param connected Connected to this network
 * @param device Device
 * @param frequency Network frequency
 * @param guid The guid of the wifi
 * @param security Security
 * @param ssid Ssid of the wlan
 * @param strength Signal strength
 * @param url Specific wifi network
 */
@Serializable@Serializable

data class GetWifiNetwork (

    /* Network channel */
    @SerialName(value = "channel") val channel: kotlin.Long? = null,

    /* Connected to this network */
    @SerialName(value = "connected") val connected: kotlin.Boolean? = null,

    /* Device */
    @SerialName(value = "device") val device: kotlin.String? = null,

    /* Network frequency */
    @SerialName(value = "frequency") val frequency: kotlin.String? = null,

    /* The guid of the wifi */
    @SerialName(value = "guid") val guid: kotlin.String? = null,

    /* Security */
    @SerialName(value = "security") val security: kotlin.String? = null,

    /* Ssid of the wlan */
    @SerialName(value = "ssid") val ssid: kotlin.String? = null,

    /* Signal strength */
    @SerialName(value = "strength") val strength: kotlin.Long? = null,

    /* Specific wifi network */
    @SerialName(value = "url") val url: kotlin.String? = null

)

