/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param bssid Access point mac address
 * @param connected Connected to the network of this connection
 * @param device Device to use for this connection
 * @param dns Dnss for the connection
 * @param ipAddress Ip address for the connection
 * @param lastConnected Date and time for when the connection was last successfully connected
 * @param mac Network adapter mac address
 * @param name Name or id of the connection
 * @param netmask Netmask for the connection
 * @param security The security method used by the connection
 * @param type Connection type e.g. 802-11-wireless
 * @param url Specific connection
 * @param uuid Uuid of the connection
 */
@Serializable@Serializable

data class GetWifiConnection (

    /* Access point mac address */
    @SerialName(value = "bssid") val bssid: kotlin.String? = null,

    /* Connected to the network of this connection */
    @SerialName(value = "connected") val connected: kotlin.Boolean? = null,

    /* Device to use for this connection */
    @SerialName(value = "device") val device: kotlin.String? = null,

    /* Dnss for the connection */
    @SerialName(value = "dns") val dns: kotlin.String? = null,

    /* Ip address for the connection */
    @SerialName(value = "ip_address") val ipAddress: kotlin.String? = null,

    /* Date and time for when the connection was last successfully connected */
    @SerialName(value = "last_connected") val lastConnected: kotlin.String? = null,

    /* Network adapter mac address */
    @SerialName(value = "mac") val mac: kotlin.String? = null,

    /* Name or id of the connection */
    @SerialName(value = "name") val name: kotlin.String? = null,

    /* Netmask for the connection */
    @SerialName(value = "netmask") val netmask: kotlin.String? = null,

    /* The security method used by the connection */
    @SerialName(value = "security") val security: kotlin.String? = null,

    /* Connection type e.g. 802-11-wireless */
    @SerialName(value = "type") val type: kotlin.String? = null,

    /* Specific connection */
    @SerialName(value = "url") val url: kotlin.String? = null,

    /* Uuid of the connection */
    @SerialName(value = "uuid") val uuid: kotlin.String? = null

)

