/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models

import com.federicogiordano.mirage.models.Cart

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param angle The current angle of the hook
 * @param available Boolean indicating if the hook available on this robot
 * @param braked Boolean indicating if the hook brake is activated
 * @param cart 
 * @param cartAttached Boolean indicating if a trolley is currently attached
 * @param height The current height of the hook
 * @param length The length of the hook
 */
@Serializable@Serializable

data class HookStatus (

    /* The current angle of the hook */
    @SerialName(value = "angle") val angle: kotlin.Float? = null,

    /* Boolean indicating if the hook available on this robot */
    @SerialName(value = "available") val available: kotlin.Boolean? = null,

    /* Boolean indicating if the hook brake is activated */
    @SerialName(value = "braked") val braked: kotlin.Boolean? = null,

    @SerialName(value = "cart") val cart: Cart? = null,

    /* Boolean indicating if a trolley is currently attached */
    @SerialName(value = "cart_attached") val cartAttached: kotlin.Boolean? = null,

    /* The current height of the hook */
    @SerialName(value = "height") val height: kotlin.Float? = null,

    /* The length of the hook */
    @SerialName(value = "length") val length: kotlin.Float? = null

)

