/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param feature Min length: 1, Max length: 63
 * @param icon 
 * @param name Min length: 1, Max length: 63
 * @param priority 
 * @param createdById 
 * @param guid 
 */
@Serializable@Serializable

data class PostMissionGroups (

    /* Min length: 1, Max length: 63 */
    @SerialName(value = "feature") @Required val feature: kotlin.String,

    @SerialName(value = "icon") @Required val icon: com.federicogiordano.mirage.infrastructure.Base64ByteArray,

    /* Min length: 1, Max length: 63 */
    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "priority") @Required val priority: kotlin.Long,

    @SerialName(value = "created_by_id") val createdById: kotlin.String? = null,

    @SerialName(value = "guid") val guid: kotlin.String? = null

)

