/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param robotIp 
 * @param worldModel 
 */
@Serializable@Serializable

data class PostWorldModel (

    @SerialName(value = "robot_ip") val robotIp: kotlin.String? = null,

    @SerialName(value = "world_model") val worldModel: kotlin.collections.List<kotlin.String>? = null

)

