/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param missionId 
 * @param message Max length: 200
 * @param parameters 
 * @param priority 
 */
@Serializable@Serializable

data class PostMissionQueues (

    @SerialName(value = "mission_id") @Required val missionId: kotlin.String,

    /* Max length: 200 */
    @SerialName(value = "message") val message: kotlin.String? = null,

    @SerialName(value = "parameters") val parameters: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "priority") val priority: kotlin.Long? = null

)

