/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param actionType Min length: 1, Max length: 255
 * @param missionId 
 * @param parameters 
 * @param priority 
 * @param guid 
 * @param scopeReference 
 */
@Serializable@Serializable

data class PostMissionActions (

    /* Min length: 1, Max length: 255 */
    @SerialName(value = "action_type") @Required val actionType: kotlin.String,

    @SerialName(value = "mission_id") @Required val missionId: kotlin.String,

    @SerialName(value = "parameters") @Required val parameters: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "priority") @Required val priority: kotlin.Long,

    @SerialName(value = "guid") val guid: kotlin.String? = null,

    @SerialName(value = "scope_reference") val scopeReference: kotlin.String? = null

)

