/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param ssid 
 * @param address 
 * @param device 
 * @param dns 
 * @param gateway 
 * @param netmask 
 * @param security 
 */
@Serializable@Serializable

data class PostWifiConnection (

    @SerialName(value = "ssid") @Required val ssid: kotlin.String,

    @SerialName(value = "address") val address: kotlin.String? = null,

    @SerialName(value = "device") val device: kotlin.String? = null,

    @SerialName(value = "dns") val dns: kotlin.String? = null,

    @SerialName(value = "gateway") val gateway: kotlin.String? = null,

    @SerialName(value = "netmask") val netmask: kotlin.String? = null,

    @SerialName(value = "security") val security: kotlin.String? = null

)

