/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param goalPosId 
 * @param missionId 
 * @param startPosId 
 * @param createdById 
 * @param guid 
 */
@Serializable@Serializable

data class PostPositionTransitionLists (

    @SerialName(value = "goal_pos_id") @Required val goalPosId: kotlin.String,

    @SerialName(value = "mission_id") @Required val missionId: kotlin.String,

    @SerialName(value = "start_pos_id") @Required val startPosId: kotlin.String,

    @SerialName(value = "created_by_id") val createdById: kotlin.String? = null,

    @SerialName(value = "guid") val guid: kotlin.String? = null

)

