/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param mapId 
 * @param polygon 
 * @param typeId 
 * @param actions 
 * @param createdById 
 * @param guid 
 * @param name Max length: 255
 */
@Serializable@Serializable

data class PostAreaEvents (

    @SerialName(value = "map_id") @Required val mapId: kotlin.String,

    @SerialName(value = "polygon") @Required val polygon: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "type_id") @Required val typeId: kotlin.Long,

    @SerialName(value = "actions") val actions: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "created_by_id") val createdById: kotlin.String? = null,

    @SerialName(value = "guid") val guid: kotlin.String? = null,

    /* Max length: 255 */
    @SerialName(value = "name") val name: kotlin.String? = null

)

