/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param name Min length: 2, Max length: 255
 * @param password 
 * @param userGroupId 
 * @param username Min length: 2, Max length: 63
 * @param createdById 
 * @param dashboardId 
 * @param email 
 * @param guid 
 * @param pincode 
 * @param singleDashboard 
 */
@Serializable@Serializable

data class PostUsers (

    /* Min length: 2, Max length: 255 */
    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "password") @Required val password: kotlin.String,

    @SerialName(value = "user_group_id") @Required val userGroupId: kotlin.String,

    /* Min length: 2, Max length: 63 */
    @SerialName(value = "username") @Required val username: kotlin.String,

    @SerialName(value = "created_by_id") val createdById: kotlin.String? = null,

    @SerialName(value = "dashboard_id") val dashboardId: kotlin.String? = null,

    @SerialName(value = "email") val email: kotlin.String? = null,

    @SerialName(value = "guid") val guid: kotlin.String? = null,

    @SerialName(value = "pincode") val pincode: kotlin.String? = null,

    @SerialName(value = "single_dashboard") val singleDashboard: kotlin.Boolean? = null

)

