/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param endpoint Min length: 1, Max length: 255
 * @param permissionType 
 * @param guid 
 */
@Serializable@Serializable

data class PostUserGroupPermission (

    /* Min length: 1, Max length: 255 */
    @SerialName(value = "endpoint") @Required val endpoint: kotlin.String,

    @SerialName(value = "permission_type") @Required val permissionType: kotlin.String,

    @SerialName(value = "guid") val guid: kotlin.String? = null

)

