/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param map 
 * @param metadata 
 * @param name Min length: 1, Max length: 40
 * @param originTheta 
 * @param originX 
 * @param originY 
 * @param resolution 
 * @param sessionId 
 * @param createdById 
 * @param guid 
 * @param oneWayMap 
 */
@Serializable@Serializable

data class PostMaps (

    @SerialName(value = "map") @Required val map: com.federicogiordano.mirage.infrastructure.Base64ByteArray,

    @SerialName(value = "metadata") @Required val metadata: com.federicogiordano.mirage.infrastructure.Base64ByteArray,

    /* Min length: 1, Max length: 40 */
    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "origin_theta") @Required val originTheta: kotlin.Float,

    @SerialName(value = "origin_x") @Required val originX: kotlin.Float,

    @SerialName(value = "origin_y") @Required val originY: kotlin.Float,

    @SerialName(value = "resolution") @Required val resolution: kotlin.Float,

    @SerialName(value = "session_id") @Required val sessionId: kotlin.String,

    @SerialName(value = "created_by_id") val createdById: kotlin.String? = null,

    @SerialName(value = "guid") val guid: kotlin.String? = null,

    @SerialName(value = "one_way_map") val oneWayMap: com.federicogiordano.mirage.infrastructure.Base64ByteArray? = null

)

