/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param orientationOffset 
 * @param posId 
 * @param xOffset 
 * @param yOffset 
 * @param guid 
 */
@Serializable@Serializable

data class PostDockingOffsets (

    @SerialName(value = "orientation_offset") @Required val orientationOffset: kotlin.Float,

    @SerialName(value = "pos_id") @Required val posId: kotlin.String,

    @SerialName(value = "x_offset") @Required val xOffset: kotlin.Float,

    @SerialName(value = "y_offset") @Required val yOffset: kotlin.Float,

    @SerialName(value = "guid") val guid: kotlin.String? = null

)

