/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param pathGuideGuid 
 * @param posGuid 
 * @param posType 
 * @param guid 
 * @param priority 
 */
@Serializable@Serializable

data class PostPathGuidesPositions (

    @SerialName(value = "path_guide_guid") @Required val pathGuideGuid: kotlin.String,

    @SerialName(value = "pos_guid") @Required val posGuid: kotlin.String,

    @SerialName(value = "pos_type") @Required val posType: kotlin.String,

    @SerialName(value = "guid") val guid: kotlin.String? = null,

    @SerialName(value = "priority") val priority: kotlin.Long? = null

)

