/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param name Min length: 1, Max length: 40
 * @param sound 
 * @param createdById 
 * @param guid 
 * @param note Max length: 255
 * @param volume 
 */
@Serializable@Serializable

data class PostSounds (

    /* Min length: 1, Max length: 40 */
    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "sound") @Required val sound: com.federicogiordano.mirage.infrastructure.OctetByteArray,

    @SerialName(value = "created_by_id") val createdById: kotlin.String? = null,

    @SerialName(value = "guid") val guid: kotlin.String? = null,

    /* Max length: 255 */
    @SerialName(value = "note") val note: kotlin.String? = null,

    @SerialName(value = "volume") val volume: kotlin.Long? = null

)

