/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param driveHeight 
 * @param entryHeight 
 * @param lockHeight 
 * @param name Min length: 1, Max length: 40
 * @param qw 
 * @param qx 
 * @param qy 
 * @param qz 
 * @param standard 
 * @param x 
 * @param y 
 * @param z 
 * @param createdById 
 * @param guid 
 */
@Serializable@Serializable

data class PostCartCalibrations (

    @SerialName(value = "drive_height") @Required val driveHeight: kotlin.Long,

    @SerialName(value = "entry_height") @Required val entryHeight: kotlin.Long,

    @SerialName(value = "lock_height") @Required val lockHeight: kotlin.Long,

    /* Min length: 1, Max length: 40 */
    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "qw") @Required val qw: kotlin.Float,

    @SerialName(value = "qx") @Required val qx: kotlin.Float,

    @SerialName(value = "qy") @Required val qy: kotlin.Float,

    @SerialName(value = "qz") @Required val qz: kotlin.Float,

    @SerialName(value = "standard") @Required val standard: kotlin.Boolean,

    @SerialName(value = "x") @Required val x: kotlin.Float,

    @SerialName(value = "y") @Required val y: kotlin.Float,

    @SerialName(value = "z") @Required val z: kotlin.Float,

    @SerialName(value = "created_by_id") val createdById: kotlin.String? = null,

    @SerialName(value = "guid") val guid: kotlin.String? = null

)

