/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param autogenerated 
 * @param footprint Max length: 255
 * @param goalPosId 
 * @param lastUsed 
 * @param length 
 * @param mapCrc Min length: 32, Max length: 32
 * @param path 
 * @param startPosId 
 * @param time 
 * @param valid 
 * @param guid 
 */
@Serializable@Serializable

data class PostPaths (

    @SerialName(value = "autogenerated") @Required val autogenerated: kotlin.Boolean,

    /* Max length: 255 */
    @SerialName(value = "footprint") @Required val footprint: kotlin.String,

    @SerialName(value = "goal_pos_id") @Required val goalPosId: kotlin.String,

    @SerialName(value = "last_used") @Required val lastUsed: kotlin.String,

    @SerialName(value = "length") @Required val length: kotlin.Float,

    /* Min length: 32, Max length: 32 */
    @SerialName(value = "map_crc") @Required val mapCrc: kotlin.String,

    @SerialName(value = "path") @Required val path: com.federicogiordano.mirage.infrastructure.Base64ByteArray,

    @SerialName(value = "start_pos_id") @Required val startPosId: kotlin.String,

    @SerialName(value = "time") @Required val time: kotlin.Float,

    @SerialName(value = "valid") @Required val valid: kotlin.Boolean,

    @SerialName(value = "guid") val guid: kotlin.String? = null

)

