/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param label Min length: 1, Max length: 50
 * @param `value` 
 */
@Serializable@Serializable

data class PostRegister (

    /* Min length: 1, Max length: 50 */
    @SerialName(value = "label") val label: kotlin.String? = null,

    @SerialName(value = "value") val `value`: kotlin.Float? = null

)

