/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param mapId 
 * @param name Min length: 1, Max length: 40
 * @param orientation 
 * @param posX 
 * @param posY 
 * @param typeId 
 * @param createdById 
 * @param guid 
 * @param parentId 
 */
@Serializable@Serializable

data class PostPositions (

    @SerialName(value = "map_id") @Required val mapId: kotlin.String,

    /* Min length: 1, Max length: 40 */
    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "orientation") @Required val orientation: kotlin.Float,

    @SerialName(value = "pos_x") @Required val posX: kotlin.Float,

    @SerialName(value = "pos_y") @Required val posY: kotlin.Float,

    @SerialName(value = "type_id") @Required val typeId: kotlin.Long,

    @SerialName(value = "created_by_id") val createdById: kotlin.String? = null,

    @SerialName(value = "guid") val guid: kotlin.String? = null,

    @SerialName(value = "parent_id") val parentId: kotlin.String? = null

)

