/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param dashboardId 
 * @param guid 
 * @param settings 
 */
@Serializable@Serializable

data class PostDashboardWidgets (

    @SerialName(value = "dashboard_id") @Required val dashboardId: kotlin.String,

    @SerialName(value = "guid") val guid: kotlin.String? = null,

    @SerialName(value = "settings") val settings: kotlin.String? = null

)

