/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param barDistance 
 * @param barLength 
 * @param height 
 * @param length 
 * @param name Min length: 1, Max length: 40
 * @param offsetX 
 * @param offsetY 
 * @param width 
 * @param createdById 
 * @param guid 
 */
@Serializable@Serializable

data class PostShelfTypes (

    @SerialName(value = "bar_distance") @Required val barDistance: kotlin.Float,

    @SerialName(value = "bar_length") @Required val barLength: kotlin.Float,

    @SerialName(value = "height") @Required val height: kotlin.Float,

    @SerialName(value = "length") @Required val length: kotlin.Float,

    /* Min length: 1, Max length: 40 */
    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "offset_x") @Required val offsetX: kotlin.Float,

    @SerialName(value = "offset_y") @Required val offsetY: kotlin.Float,

    @SerialName(value = "width") @Required val width: kotlin.Float,

    @SerialName(value = "created_by_id") val createdById: kotlin.String? = null,

    @SerialName(value = "guid") val guid: kotlin.String? = null

)

