/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param description Min length: 1, Max length: 2056
 * @param guid 
 */
@Serializable@Serializable

data class PostServiceBooks (

    /* Min length: 1, Max length: 2056 */
    @SerialName(value = "description") @Required val description: kotlin.String,

    @SerialName(value = "guid") val guid: kotlin.String? = null

)

