/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param cartCalibrationId 
 * @param cartTypeId 
 * @param name Min length: 1, Max length: 40
 */
@Serializable@Serializable

data class PutCart (

    @SerialName(value = "cart_calibration_id") val cartCalibrationId: kotlin.String? = null,

    @SerialName(value = "cart_type_id") val cartTypeId: kotlin.String? = null,

    /* Min length: 1, Max length: 40 */
    @SerialName(value = "name") val name: kotlin.String? = null

)

