/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param driveHeight 
 * @param entryHeight 
 * @param lockHeight 
 * @param name Min length: 1, Max length: 40
 * @param qw 
 * @param qx 
 * @param qy 
 * @param qz 
 * @param standard 
 * @param x 
 * @param y 
 * @param z 
 */
@Serializable@Serializable

data class PutCartCalibration (

    @SerialName(value = "drive_height") val driveHeight: kotlin.Long? = null,

    @SerialName(value = "entry_height") val entryHeight: kotlin.Long? = null,

    @SerialName(value = "lock_height") val lockHeight: kotlin.Long? = null,

    /* Min length: 1, Max length: 40 */
    @SerialName(value = "name") val name: kotlin.String? = null,

    @SerialName(value = "qw") val qw: kotlin.Float? = null,

    @SerialName(value = "qx") val qx: kotlin.Float? = null,

    @SerialName(value = "qy") val qy: kotlin.Float? = null,

    @SerialName(value = "qz") val qz: kotlin.Float? = null,

    @SerialName(value = "standard") val standard: kotlin.Boolean? = null,

    @SerialName(value = "x") val x: kotlin.Float? = null,

    @SerialName(value = "y") val y: kotlin.Float? = null,

    @SerialName(value = "z") val z: kotlin.Float? = null

)

