/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param height 
 * @param length 
 * @param name Min length: 1, Max length: 40
 * @param offsetLockedWheels 
 * @param width 
 */
@Serializable@Serializable

data class PutCartType (

    @SerialName(value = "height") val height: kotlin.Float? = null,

    @SerialName(value = "length") val length: kotlin.Float? = null,

    /* Min length: 1, Max length: 40 */
    @SerialName(value = "name") val name: kotlin.String? = null,

    @SerialName(value = "offset_locked_wheels") val offsetLockedWheels: kotlin.Float? = null,

    @SerialName(value = "width") val width: kotlin.Float? = null

)

