/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param orientationOffset 
 * @param xOffset 
 * @param yOffset 
 */
@Serializable@Serializable

data class PutDockingOffset (

    @SerialName(value = "orientation_offset") val orientationOffset: kotlin.Float? = null,

    @SerialName(value = "x_offset") val xOffset: kotlin.Float? = null,

    @SerialName(value = "y_offset") val yOffset: kotlin.Float? = null

)

