/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param address 
 * @param name Min length: 1, Max length: 255
 * @param numInputs 
 * @param numOutputs 
 * @param type Choices are: { \" bluetooth \" , \" wise \" }
 */
@Serializable@Serializable

data class PutIoModule (

    @SerialName(value = "address") val address: kotlin.String? = null,

    /* Min length: 1, Max length: 255 */
    @SerialName(value = "name") val name: kotlin.String? = null,

    @SerialName(value = "num_inputs") val numInputs: kotlin.Long? = null,

    @SerialName(value = "num_outputs") val numOutputs: kotlin.Long? = null,

    /* Choices are: { \" bluetooth \" , \" wise \" } */
    @SerialName(value = "type") val type: kotlin.String? = null

)

