/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param cmd 
 * @param description Max length: 200
 * @param missionId 
 * @param priority 
 */
@Serializable@Serializable

data class PutMissionQueue (

    @SerialName(value = "cmd") val cmd: kotlin.Long? = null,

    /* Max length: 200 */
    @SerialName(value = "description") val description: kotlin.String? = null,

    @SerialName(value = "mission_id") val missionId: kotlin.String? = null,

    @SerialName(value = "priority") val priority: kotlin.Long? = null

)

