/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param feature Min length: 1, Max length: 63
 * @param icon 
 * @param name Min length: 1, Max length: 63
 * @param priority 
 */
@Serializable@Serializable

data class PutMissionGroup (

    /* Min length: 1, Max length: 63 */
    @SerialName(value = "feature") val feature: kotlin.String? = null,

    @SerialName(value = "icon") val icon: com.federicogiordano.mirage.infrastructure.Base64ByteArray? = null,

    /* Min length: 1, Max length: 63 */
    @SerialName(value = "name") val name: kotlin.String? = null,

    @SerialName(value = "priority") val priority: kotlin.Long? = null

)

