/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param description Max length: 255
 * @param groupId 
 * @param hidden 
 * @param name Min length: 1, Max length: 255
 * @param sessionId 
 */
@Serializable@Serializable

data class PutMission (

    /* Max length: 255 */
    @SerialName(value = "description") val description: kotlin.String? = null,

    @SerialName(value = "group_id") val groupId: kotlin.String? = null,

    @SerialName(value = "hidden") val hidden: kotlin.Boolean? = null,

    /* Min length: 1, Max length: 255 */
    @SerialName(value = "name") val name: kotlin.String? = null,

    @SerialName(value = "session_id") val sessionId: kotlin.String? = null

)

