/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param parameters 
 * @param priority 
 * @param scopeReference 
 */
@Serializable@Serializable

data class PutMissionAction (

    @SerialName(value = "parameters") val parameters: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "priority") val priority: kotlin.Long? = null,

    @SerialName(value = "scope_reference") val scopeReference: kotlin.String? = null

)

