/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param dashboardId 
 * @param email 
 * @param name Min length: 2, Max length: 255
 * @param password 
 * @param pincode 
 * @param singleDashboard 
 * @param userGroupId 
 * @param username Min length: 2, Max length: 63
 */
@Serializable@Serializable

data class PutMe (

    @SerialName(value = "dashboard_id") val dashboardId: kotlin.String? = null,

    @SerialName(value = "email") val email: kotlin.String? = null,

    /* Min length: 2, Max length: 255 */
    @SerialName(value = "name") val name: kotlin.String? = null,

    @SerialName(value = "password") val password: kotlin.String? = null,

    @SerialName(value = "pincode") val pincode: kotlin.String? = null,

    @SerialName(value = "single_dashboard") val singleDashboard: kotlin.Boolean? = null,

    @SerialName(value = "user_group_id") val userGroupId: kotlin.String? = null,

    /* Min length: 2, Max length: 63 */
    @SerialName(value = "username") val username: kotlin.String? = null

)

