/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param map 
 * @param metadata 
 * @param name Min length: 1, Max length: 40
 * @param oneWayMap 
 * @param originTheta 
 * @param originX 
 * @param originY 
 * @param resolution 
 */
@Serializable@Serializable

data class PutMap (

    @SerialName(value = "map") val map: com.federicogiordano.mirage.infrastructure.Base64ByteArray? = null,

    @SerialName(value = "metadata") val metadata: com.federicogiordano.mirage.infrastructure.Base64ByteArray? = null,

    /* Min length: 1, Max length: 40 */
    @SerialName(value = "name") val name: kotlin.String? = null,

    @SerialName(value = "one_way_map") val oneWayMap: com.federicogiordano.mirage.infrastructure.Base64ByteArray? = null,

    @SerialName(value = "origin_theta") val originTheta: kotlin.Float? = null,

    @SerialName(value = "origin_x") val originX: kotlin.Float? = null,

    @SerialName(value = "origin_y") val originY: kotlin.Float? = null,

    @SerialName(value = "resolution") val resolution: kotlin.Float? = null

)

