/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param coilId 
 * @param missionId 
 * @param name Min length: 1, Max length: 200
 * @param parameters 
 */
@Serializable@Serializable

data class PutModbusMission (

    @SerialName(value = "coil_id") val coilId: kotlin.Long? = null,

    @SerialName(value = "mission_id") val missionId: kotlin.String? = null,

    /* Min length: 1, Max length: 200 */
    @SerialName(value = "name") val name: kotlin.String? = null,

    @SerialName(value = "parameters") val parameters: kotlin.collections.List<kotlin.String>? = null

)

