/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param mapId 
 * @param name Min length: 1, Max length: 40
 * @param orientation 
 * @param parentId 
 * @param posX 
 * @param posY 
 * @param typeId 
 */
@Serializable@Serializable

data class PutPosition (

    @SerialName(value = "map_id") val mapId: kotlin.String? = null,

    /* Min length: 1, Max length: 40 */
    @SerialName(value = "name") val name: kotlin.String? = null,

    @SerialName(value = "orientation") val orientation: kotlin.Float? = null,

    @SerialName(value = "parent_id") val parentId: kotlin.String? = null,

    @SerialName(value = "pos_x") val posX: kotlin.Float? = null,

    @SerialName(value = "pos_y") val posY: kotlin.Float? = null,

    @SerialName(value = "type_id") val typeId: kotlin.Long? = null

)

