/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param mapId 
 * @param name Min length: 1, Max length: 128
 */
@Serializable@Serializable

data class PutPathGuide (

    @SerialName(value = "map_id") val mapId: kotlin.String? = null,

    /* Min length: 1, Max length: 128 */
    @SerialName(value = "name") val name: kotlin.String? = null

)

