/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param autogenerated 
 * @param footprint Max length: 255
 * @param goalPosId 
 * @param lastUsed 
 * @param length 
 * @param mapCrc Min length: 32, Max length: 32
 * @param path 
 * @param startPosId 
 * @param time 
 * @param valid 
 */
@Serializable@Serializable

data class PutPath (

    @SerialName(value = "autogenerated") val autogenerated: kotlin.Boolean? = null,

    /* Max length: 255 */
    @SerialName(value = "footprint") val footprint: kotlin.String? = null,

    @SerialName(value = "goal_pos_id") val goalPosId: kotlin.String? = null,

    @SerialName(value = "last_used") val lastUsed: kotlin.String? = null,

    @SerialName(value = "length") val length: kotlin.Float? = null,

    /* Min length: 32, Max length: 32 */
    @SerialName(value = "map_crc") val mapCrc: kotlin.String? = null,

    @SerialName(value = "path") val path: com.federicogiordano.mirage.infrastructure.Base64ByteArray? = null,

    @SerialName(value = "start_pos_id") val startPosId: kotlin.String? = null,

    @SerialName(value = "time") val time: kotlin.Float? = null,

    @SerialName(value = "valid") val valid: kotlin.Boolean? = null

)

