/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param posGuid 
 * @param priority 
 */
@Serializable@Serializable

data class PutPathGuidePosition (

    @SerialName(value = "pos_guid") val posGuid: kotlin.String? = null,

    @SerialName(value = "priority") val priority: kotlin.Long? = null

)

