/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param name Min length: 1, Max length: 40
 * @param note Max length: 255
 * @param sound 
 * @param volume 
 */
@Serializable@Serializable

data class PutSound (

    /* Min length: 1, Max length: 40 */
    @SerialName(value = "name") val name: kotlin.String? = null,

    /* Max length: 255 */
    @SerialName(value = "note") val note: kotlin.String? = null,

    @SerialName(value = "sound") val sound: com.federicogiordano.mirage.infrastructure.OctetByteArray? = null,

    @SerialName(value = "volume") val volume: kotlin.Long? = null

)

