/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param active 
 * @param description Max length: 255
 * @param name Min length: 1, Max length: 40
 */
@Serializable@Serializable

data class PutSession (

    @SerialName(value = "active") val active: kotlin.Boolean? = null,

    /* Max length: 255 */
    @SerialName(value = "description") val description: kotlin.String? = null,

    /* Min length: 1, Max length: 40 */
    @SerialName(value = "name") val name: kotlin.String? = null

)

