/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param guid 
 * @param options 
 * @param question 
 * @param timeout 
 * @param userGroup 
 */
@Serializable@Serializable

data class UserPrompt (

    @SerialName(value = "guid") val guid: kotlin.String? = null,

    @SerialName(value = "options") val options: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "question") val question: kotlin.String? = null,

    @SerialName(value = "timeout") val timeout: kotlin.Float? = null,

    @SerialName(value = "user_group") val userGroup: kotlin.String? = null

)

