/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.federicogiordano.mirage.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param name The name of the position
 * @param posGuid The global unique id across robots that identifies this position
 */
@Serializable@Serializable

data class Vias (

    /* The name of the position */
    @SerialName(value = "name") val name: kotlin.String? = null,

    /* The global unique id across robots that identifies this position */
    @SerialName(value = "pos_guid") val posGuid: kotlin.String? = null

)

